--------------------------------------------------------
--  Constraints for Table BOOKS
--------------------------------------------------------
SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
ALTER TABLE "BOOKS" ADD CONSTRAINT "BOOKS_PK" PRIMARY KEY ("BOOK_ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
TABLESPACE "USERS"  ENABLE;
ALTER TABLE "BOOKS" MODIFY ("PUBLISHER_ID" NOT NULL ENABLE);
ALTER TABLE "BOOKS" MODIFY ("PUBLISHED_DATE" NOT NULL ENABLE);
ALTER TABLE "BOOKS" MODIFY ("ISBN" NOT NULL ENABLE);
ALTER TABLE "BOOKS" MODIFY ("RATING" NOT NULL ENABLE);
ALTER TABLE "BOOKS" MODIFY ("TOTAL_PAGES" NOT NULL ENABLE);
ALTER TABLE "BOOKS" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE "BOOKS" MODIFY ("BOOK_ID" NOT NULL ENABLE);
